### ISSUE TITLE
officially support mutating middleware

### ISSUE THREAD

**Issue by mikeybtn** [koajs/compose#67] opened 2016-10-25 23:20 UTC
Because of #65, specifically `lodash.flatten`, `compose()` returns a generator based on a _copy_ of the provided array from that point in time. Any changes made to this array subsequently will no longer be reflected in the returned middleware.

Previously, one could mutate the array after calling `compose`.

**Comment by PlasmaPower** [comment] 2016-10-25 23:23
> Previously, one could mutate the array after calling compose.

Interesting, I had no idea that was possible. I'll rewrite flatten to be lazy.

**Comment by mikeybtn** [comment] 2016-10-25 23:31
> Interesting, I had no idea that was possible. 

Yeah, admittedly our usage does feel a tad unusual.. 

> I'll rewrite flatten to be lazy.

Thanks! I suppose it'd be a nice micro optimization (remove a `copy`) if you do, regardless of 'dynamic' usage like this..

**Comment by PlasmaPower** [comment] 2016-10-26 00:14
> Thanks! I suppose it'd be a nice micro optimization (remove a copy) if you do, regardless of 'dynamic' usage like this..

Actually, this is *really* bad for performance, as it means it has to be flattened every time (previously it could be cached). In fact, that makes me reconsider this, maybe we should just remove variadic argument support... making the `next` PR anyway.

**Comment by PlasmaPower** [comment] 2016-10-26 00:24
Okay, I've opened #68 and #69 to solve this. However, I'm personally in favor of just reverting the variadic argument change, as the performance cost is now high.

**Comment by conorhastings** [comment] 2016-10-26 02:24
agreed, I would vote to revert the changes published in 2.5

**Comment by mariodu** [comment] 2016-10-26 04:10
+1

**Comment by PlasmaPower** [comment] 2016-10-26 04:13
@jonathanong Might want to revert those changes sooner rather than later.

**Comment by jonathanong** [comment] 2016-10-26 06:19
can you guys explain your use-cases? this wasn't something we were ever supporting.

how much performance decrease are we talking about by doing the dynamic version?

**Comment by andrenarchy** [comment] 2016-10-26 10:49
I'm not entirely sure how koa uses koa-compose but this change definitely breaks my application. Can you revert it?

**Comment by conorhastings** [comment] 2016-10-26 11:31
@jonathanong The problem occurs if you call app.use to add any middleware after you've already triggered a call of app.callback, since this.middleware, the argument that is passed to compose is a mutable array. 

this would previously work fine as it would reference the now mutated array, but since the flatten changes the semantics by copying at call time of compose with the flatten, anything added to the middleware after the call to compose is effectively ignored.

I would think that even if this wasn't an envisioned use case, it still seems like a breaking change since it does, even if inadvertently, change the way the module works.

Thanks for all the hard work!

**Comment by ykt** [comment] 2016-10-26 14:08
Having same issue, it is breaking our App.

**Comment by mikeybtn** [comment] 2016-10-26 14:27
It seems that a patch along the following lines could preserve the object ownership, support variadic args, and not introduce any copying or dependencies:

```js
function compose(middleware) {
  if (arguments.length > 1) {
    middleware = Array.prototype.slice.call(arguments);
  }
  // ...
}
```

This wouldn't support nested flattening, e.g. `compose( [a,b], [c] )`. Not sure if that's considered an important feature.

**Comment by PlasmaPower** [comment] 2016-10-26 16:14
I think `compose([a, b], [c])` is pretty useful if you're working with lists of middleware. Maybe we should run benchmarks on these different implementations or something.

**Comment by jonathanong** [comment] 2016-10-26 18:50
yeah i'm gonna revert it now. 

> The problem occurs if you call app.use to add any middleware after you've already triggered a call of app.callback

@conorhastings why are you doing this, though?

**Comment by jonathanong** [comment] 2016-10-26 18:50
also, if this breaks usage within a 3rd party middleware/router/etc., which ones?

**Comment by jonathanong** [comment] 2016-10-26 18:59
i have published `v2.5.1` and `v3.2.1` which reverts the change. `v2.5.0` and `v3.2.0` are marked as deprecated on npm.

- changing this topic to "officially support mutating `middleware`". i see this as code-smell and would like to understand the use-case
- moving discussion to continuing variadic support in https://github.com/koajs/compose/issues/63. this is still a feature i would like to add, but we will do so only in `koa-compose@4`

**Comment by conorhastings** [comment] 2016-10-26 18:59
@jonathanong it was likely a mistake in our app code, not sure why we were doing it, definitely not purposefully relying on array mutation 😕 . Have already refactored our app code so that it will work with 2.5 , haven't experienced anything caused by external modules myself

**Comment by jonathanong** [comment] 2016-10-26 19:10
@conorhastings that's good to know!

yeah, you should be sure to do `app.listen()` or `app.callback()` only after you've added all your middleware. i think this is an oversight in the docs.

**Comment by jonathanong** [comment] 2021-08-18 03:40
instead of supporting it here, we will add an ability to configure your compose function in koa https://github.com/koajs/koa/issues/1568

**Closed by jonathanong** 2021-08-18 03:40 UTC
